services:
  - type: web
    name: digital-store
    runtime: python
    region: singapore
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: BAKONG_API_TOKEN
        sync: false
      - key: BAKONG_ACCOUNT
        value: chheak_narat@bkrt
      - key: MERCHANT_NAME
        value: NARAT CHHEAK
      - key: BAKONG_API_URL
        value: https://api-bakong.nbc.gov.kh/v1
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_SECRET_PATH
        sync: false
      - key: DATABASE_URL
        sync: false
